name = "pulse"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[durable_objects.bindings]]
name = "MEETING_ROOM"
class_name = "MeetingRoom"

[[migrations]]
tag = "v1" # Version 1 of your database/object structure
new_sqlite_classes = ["MeetingRoom"]

[observability]
enabled = true